version: '3.4'

services:
  author.command.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44305
      - ServiceBusUserName=guest
      - ServiceBusUserPassword=guest
      - ServiceBusConnection=rabbitmq
      - UseAzureServiceBus=${UseAzureServiceBus:-false}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  authoradmin.command.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44306
      - ServiceBusUserName=guest
      - ServiceBusUserPassword=guest
      - ServiceBusConnection=rabbitmq
      - UseAzureServiceBus=${UseAzureServiceBus:-false}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  author.apigateway.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api
    ports:
      - "32770:80"
    volumes:
      - ./Common/Author.Core.ApiGateway/Configurations:/app/configuration

  author.apigateway.mobile:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api
    ports:
      - "32771:80"
    volumes:
      - ./Common/Author.Core.ApiGatewayMobile/Configurations:/app/configuration