version: '3.4'

services:
  authorcommandapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44305
      - ServiceBusUserName=guest
      - ServiceBusUserPassword=guest     
      - UseAzureServiceBus=${UseAzureServiceBus:-true}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  authoradmincommandapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44306
      - ServiceBusUserName=guest
      - ServiceBusUserPassword=guest     
      - UseAzureServiceBus=${UseAzureServiceBus:-true}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  authorapigatewayweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api
    ports:
      - "32773:80"
    volumes:
      - ./Common/Author.Core.ApiGateway/ConfigurationsWeb:/app/configuration

  authorapigatewaymobile:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api
    ports:
      - "32774:80"
    volumes:
      - ./Common/Author.Core.ApiGateway/configurationMobile:/app/configuration