version: '3.4'

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:management
    ports:
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  author.command.api:
    image: ${DOCKER_REGISTRY-}authorcommandapi
    build:
      context: .
      dockerfile: CommandStack/Author.Command.API/Dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  authoradmin.command.api:
    image: ${DOCKER_REGISTRY-}authorcommandapi
    build:
      context: .
      dockerfile: CommandStack/AuthorAdmin.Command.API/Dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq